WITH CTE AS (
    SELECT
    TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
    DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
    HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
    DAYNAME(TO_TIMESTAMP(STARTED_AT)),
    {{get_day_type('STARTED_AT')}} AS DAY_TYPE,
    {{get_seasson('STARTED_AT')}} AS STATION_OF_YEAR

    FROM {{ source('demo', 'bike') }}
)

SELECT *
FROM CTE