WITH BIKE AS (
    SELECT
    DISTINCT
    START_STATIO_ID AS START_STATION_ID,
    START_STATION_NAME AS STATION_NAME,
    START_LAT AS STATION_LAT,
    START_LNG AS STATION_LGN
    FROM {{ source('demo', 'bike') }}
    
)

SELECT *
FROM BIKE